// src/pages/home.jsx
"use strict";

// TODO: webpack 配置 css modules
import styles from "./home.module.scss";
import BigImg from "~/IeoTkE4xBJ4.jpg";
import image from "~/logo.png";

export default function Home() {
  // test externals
  var obj = { id: 1001, name: "hello world" };

  // eslint-disable-next-line
  _.forIn(obj, (key, val) => {
    console.log("key, val:", key, val);
  });
  
  console.log('styles:', styles);

  return (
    <div>
      <div>
        <img src={BigImg} className={styles.bigimg} />
        <img src={image} className={styles.img} />
      </div>
    </div>
  );
}

// src/pages/home.vue
<template>
  <div>
    <p>home</p>
    <img src="../assets/logo.png" class="img" />
  </div>
</template>

<script>
  export default {
    name: "",
    created() {
    // test externals
      var obj = {
        id: 1001,
        name: 'hello world',
      }
      _.forIn(obj, (key, val, obj) => {
        console.log('key, val, obj:', key, val, obj);
      })
    }
  }
</script>

<style lang="scss" scoped>
.img {
  max-width: 300px;
}
</style>
